### ISSUE TITLE
A Typing Mistake

### ISSUE THREAD

**Issue by HPDell** [saturdaymp/XPlugins.Notifications#11]
The file `Source/SaturdayMP.XPlugins.Notifications.Droid/NotificationListener.cs` defines the member function `NotificationRecieved` of class `NotificationListener`. But at the last line of that function, a symbol `NotificationReceived` is used.

I think it’s a typing mistake. Can I simply change the member function’s name to `NotificationReceived`?

**Comment by mrbiggred** [comment]
@HPDell Thank you for spotting my typo.  Please feel free to fix and when I do another release I'll make a note that this will be a breaking change.

**Comment by mrbiggred** [comment]
Closing issue as I'm archiving this repo.
